### PR TITLE
utc time fix

### PR DESCRIPTION
**Pull request by CoolElvis**

### CODE REVIEW

**Comment by ifreecarve** [comment]
Can you provide some background on what problematic behavior is corrected by this patch?  Hard-coding the timezone seems incorrect, because (from my understanding of the spec) the times in these messages are assumed to be in the local timezone of the receiver.

**Comment by CoolElvis** [comment]
```
nmea = NMEAPlus::Decoder.new.parse('$GPRMC,000010.800,V,,,,,0.00,0.00,060180,,,N*4B')

p nmea.utc_time

#=> 2080-01-06 00:00:10 +0300

# Because my local timezone is '+0300' 

p nmea.utc_time.utc

#=> 2080-01-05 21:00:10 UTC

# But nmea.utc_time should be 2080-01-06 00:00:10 UTC
```

**Comment by CoolElvis** [comment]
` Time.now` uses local timezone  by default, but  in case nmea.utc_time it should not.

**Comment by ifreecarve** [comment]
OK, I see the problem.  I will have to make similar fixes to the AIS portion of the library.  Thanks for pointing this out!

**Pull request merged**
